CREATE TABLE member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    nickname VARCHAR(255),
    role VARCHAR(255),
    avatar VARCHAR(255)
);

CREATE TABLE application (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    member_id BIGINT NOT NULL REFERENCES member(id),
    company VARCHAR(255) NOT NULL,
    position VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    applied_date DATE,
    deadline DATE,
    interview_date DATE,
    interview_time TIME(6),
    link VARCHAR(255),
    memo VARCHAR(1000),
    source VARCHAR(255),
    external_job_id VARCHAR(255)
);
