-- Existing Hibernate-managed installations may already contain these columns.
ALTER TABLE member ADD COLUMN IF NOT EXISTS auth_version BIGINT;
UPDATE member SET auth_version = 0 WHERE auth_version IS NULL;
ALTER TABLE member ALTER COLUMN auth_version SET DEFAULT 0;
ALTER TABLE member ALTER COLUMN auth_version SET NOT NULL;

ALTER TABLE application ADD COLUMN IF NOT EXISTS version BIGINT;
UPDATE application SET version = 0 WHERE version IS NULL;
ALTER TABLE application ALTER COLUMN version SET DEFAULT 0;
ALTER TABLE application ALTER COLUMN version SET NOT NULL;

CREATE TABLE IF NOT EXISTS schedule_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    application_id BIGINT NOT NULL REFERENCES application(id),
    type VARCHAR(255) NOT NULL,
    title VARCHAR(80) NOT NULL,
    event_date DATE NOT NULL,
    event_time TIME(6),
    state VARCHAR(255) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);
UPDATE schedule_event SET version = 0 WHERE version IS NULL;
ALTER TABLE schedule_event ALTER COLUMN version SET DEFAULT 0;
ALTER TABLE schedule_event ALTER COLUMN version SET NOT NULL;

CREATE INDEX IF NOT EXISTS application_member_id_idx ON application(member_id);
CREATE INDEX IF NOT EXISTS schedule_event_application_date_idx ON schedule_event(application_id, event_date);
-- Legacy dates stay intact. The existing API converts them only when edited.
