spring:
  config:
    import: optional:application-secret.yml
  datasource:
    url: jdbc:mysql://localhost:3306/jobtracker?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
jwt:
  expiration-ms: 3600000