spring:
  flyway:
    enabled: false
  config:
    import: optional:application-secret.yml
  session:
    timeout: 7d
    jdbc:
      initialize-schema: always
      schema: classpath:db/session-mysql.sql
  # 기본 프로파일 = 로컬 개발(MySQL)
  datasource:
    url: jdbc:mysql://localhost:3306/jobtracker?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
